const IMAGES = {
  portrait: new URL("./assets/Portrait.png", import.meta.url).href,
  Kirke: new URL("./assets/HvamKirke.jpg", import.meta.url).href,
  sunday: new URL("./assets/Utsikt.jpg", import.meta.url).href,
  accommodation: new URL("./assets/Rom.jpg", import.meta.url).href,
  ceremony: new URL("./assets/Hovedbygning.jpg", import.meta.url).href,
  transport: new URL("./assets/Hovedbygning.jpg", import.meta.url).href,
  weddingDinner: new URL("./assets/Vestfløy2.jpg", import.meta.url).href,
  lemon: new URL("./assets/sitron.png", import.meta.url).href,
  lemonBranch: new URL("./assets/Sitron2.png", import.meta.url).href,
  flowers: new URL("./assets/RSVP.png", import.meta.url).href,
  meetUp: new URL("./assets/wedding-couple.png", import.meta.url).href,
  rings: new URL("./assets/rings.png", import.meta.url).href,
  camera: new URL("./assets/photo-camera.png", import.meta.url).href,
  cheers: new URL("./assets/cheers.png", import.meta.url).href,
  table: new URL("./assets/wedding-dinner.png", import.meta.url).href,
  dinner: new URL("./assets/dinner.png", import.meta.url).href,
  dj: new URL("./assets/dj-music.png", import.meta.url).href,
  cake: new URL("./assets/cake.png", import.meta.url).href,
  discoBall: new URL("./assets/disco-ball.png", import.meta.url).href,
  nightFood: new URL("./assets/night-food.png", import.meta.url).href,
  moon: new URL("./assets/moon.png", import.meta.url).href,
  arch: new URL("./assets/wedding-arch.png", import.meta.url).href,
};

export default IMAGES;
